### ISSUE TITLE
Error when reading multiple files of ROMS_native

### ISSUE THREAD

**Issue by MarianoTonini** [OpenDrift/opendrift#1467]
Hello everyone, 
                        when I try to read several files with the ROMS_native.py reader from the same simulation (example: croco_avg_00*.nc), it fails to concatenate them. Apparently it does not find the correctly time dimension. 
The files already have several records each, they are not single-record files. 
I would appreciatte any help on this matter. 

The output error is as follows:

Traceback (most recent call last):
  File "/home/ubuntu/opendrift/opendrift/readers/reader_ROMS_native.py", line 160, in __init__
    self.Dataset = xr.open_mfdataset(filename,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/opendrift/lib/python3.11/site-packages/xarray/backends/api.py", line 1607, in open_mfdataset
    combined = combine_by_coords(
               ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/opendrift/lib/python3.11/site-packages/xarray/core/combine.py", line 973, in combine_by_coords
    concatenated_grouped_by_data_vars = tuple(
                                        ^^^^^^
  File "/home/ubuntu/miniconda3/envs/opendrift/lib/python3.11/site-packages/xarray/core/combine.py", line 974, in <genexpr>
    _combine_single_variable_hypercube(
  File "/home/ubuntu/miniconda3/envs/opendrift/lib/python3.11/site-packages/xarray/core/combine.py", line 634, in _combine_single_variable_hypercube
    combined_ids, concat_dims = _infer_concat_order_from_coords(list(datasets))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/opendrift/lib/python3.11/site-packages/xarray/core/combine.py", line 159, in _infer_concat_order_from_coords
    raise ValueError(
ValueError: Could not find any dimension coordinates to use to order the datasets for concatenation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/opendrift/examples/./CROCO_romsnative_drift03_hourly.py", line 27, in <module>
    croco_native = reader_ROMS_native.Reader('/media/ubuntu/SATA3/CROCO/croco_v121/GN_GSJOS_22/nest_avg_drift03hourly_opendrift*.nc');
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/opendrift/opendrift/readers/reader_ROMS_native.py", line 168, in __init__
    raise ValueError(e)
ValueError: Could not find any dimension coordinates to use to order the datasets for concatenation

**Comment by knutfrode** [comment]
You can also merge the files manually with xarray.open_mfdataset, and then
create a reader from this dataset:

ds = xr.open_mfdataset(.....)
r = Reader(ds)

**Comment by MarianoTonini** [comment]
Thanks you Knut! I will try merge the files manually. 

Mariano.
