### ISSUE TITLE
problem with reader

### ISSUE THREAD

**Issue by llx206** [OpenDrift/opendrift#271]
Dear authors,
When I run the leeway example using the current data such as the attachment, but some errors occurred as followed:
17:29:52 INFO: Opening dataset: E:\project\oilspill_rescue\operation_curr_wind\bhs_curr\bhs_cur_2020040812_2.nc
17:29:52 INFO: Opening file with Dataset
17:29:52 DEBUG: Finding coordinate variables.
17:29:52 DEBUG: Parsing variable: lon
17:29:52 DEBUG: Parsing variable: lat
17:29:52 DEBUG: Parsing variable: time
17:29:52 DEBUG: Parsing variable: u
17:29:52 DEBUG: Parsing variable: v
0.05474348
Traceback (most recent call last):
  File "E:/project/oilspill_rescue/pycharm_project/opendrift/opendrift-master/examples/test_leeway_bh_200410.py", line 13, in <module>
    'E:\\project\\oilspill_rescue\\operation_curr_wind\\bhs_curr\\bhs_cur_2020040812_2.nc')
  File "E:\project\oilspill_rescue\pycharm_project\opendrift\opendrift-master\opendrift\readers\reader_netCDF_CF_generic.py", line 172, in __init__
    **raise ValueError('delta_y is not constant!')
ValueError: delta_y is not constant!**

There are no variables x and y, but include variables of longitude and latitude in the NC file. In addition, the grid spacing is different in latitude.

Does ‘reader_netCDF_CF_generic’ apply only to data with even grid spacing in longitude or latitude?

thank you
[bhs_cur_2020040812_2.zip](https://github.com/OpenDrift/opendrift/files/4464120/bhs_cur_2020040812_2.zip)

**Comment by knutfrode** [comment]
When lon and lat are 1D-arrays, as here, then presently delta-lon and delta-lat have to be constant.
But this could be changed, I will try to do that soon.

**Comment by llx206** [comment]
Thank you very much! please let me know after you finish the modification, then i will download the latest version.

**Comment by JSoto-Nav** [comment]
Hello,

I'm trying to run a simulation using models outputs with 1d arrays for longitude and latitude. I get the same error:

**ValueError: delta_y is not constant!**

Is there a way to use 'reader_netCDF_CF_generic’ with uneven spaced 1d latitude?
