### ISSUE TITLE
OpenDrift problem with bathymetry GEBCO data

### ISSUE THREAD

**Issue by gauteh** [OpenDrift/opendrift#727]
### Discussed in https://github.com/OpenDrift/opendrift/discussions/726

<div type='discussions-op-text'>

<sup>Originally posted by **oceandiff** October  8, 2021</sup>
Hi all, I have a problem with a test I'm running with 2 netcdf files, the first one with u, v velocities and time, the second one with lon, lat and sea_floor_depth_below_sea_level. I read the 2 files with a generic reader like this:

reader_uv = reader_netCDF_CF_generic.Reader(o.test_data_folder() + 'med-cmcc-cur-an-fc-h_1633536911380.nc')
reader_gebco = reader_netCDF_CF_generic.Reader(o.test_data_folder() + 'gebco_2021.nc')

and afther this I add the reader:

    o.add_reader([reader_uv, reader_gebco])

This is my output when I try to run the test model:

```
11:14:55 INFO    opendrift.models.basemodel: OpenDriftSimulation initialised (version 1.7.1)
11:14:55 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1633536911380.nc
11:14:55 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
11:14:55 INFO    opendrift.readers.basereader: Variable y_sea_water_velocity will be rotated from northward_sea_water_velocity
11:14:55 INFO    opendrift.readers.basereader: Variable x_sea_water_velocity will be rotated from eastward_sea_water_velocity
11:14:55 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\gebco_2021.nc
11:14:55 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
Traceback (most recent call last):
  File "C:\Users\opendrift\examples\test\example_bathy.py", line 34, in <module>
    o.run(time_step=600, time_step_output=3600, duration=timedelta(hours=48))
  File "c:\users\opendrift\opendrift\models\basemodel.py", line 2328, in run
    self.closest_ocean_points(self.elements_scheduled.lon,
  File "c:\users\opendrift\opendrift\models\basemodel.py", line 1399, in closest_ocean_points
    land = o.get_environment(['land_binary_mask'],
  File "c:\users\opendrift\opendrift\models\basemodel.py", line 940, in get_environment
    self.discard_irrelevant_readers()
  File "c:\users\opendrift\opendrift\models\basemodel.py", line 910, in discard_irrelevant_readers
    for readername in self.readers:
RuntimeError: OrderedDict mutated during iteration
(opendrift) PS C:\Users\opendrift\examples\test>
```

Thanks in advance to anyone trying to help me ;)</div>

**Comment by oceandiff** [comment]
Hi Gaute, thanks for your help, but I've just updated opendrift with:

`conda env update -f environment.yml`

and the problem persists

**Comment by knutfrode** [comment]
Hi,

This just updates the dependencies, and not OpenDrift itself.
To update OpenDrift, you should type `git pull` in the OpenDrift source folder.
I believe you should also type `pip install -e .` since you also updated the dependencies (which is good to do from time to time).

**Comment by oceandiff** [comment]
Hi,
here you are the result of print(reader_current) and print(reader_gebco):

`Reader: c:\users\opendrift\tests\test_data\gebco_2021.nc
Projection:
  +proj=latlong
Coverage: [degrees]
  xmin: -0.589583   xmax: 23.639583   step: 0.00416667   numx: 5816
  ymin: 34.960417   ymax: 46.139583   step: 0.00416667   numy: 2683
  Corners (lon, lat):
    ( -0.59,  46.14)  ( 23.64,  46.14)
    ( -0.59,  34.96)  ( 23.64,  34.96)
Vertical levels [m]:
  Not specified
Available time range:
  start: None   end: None   step: None
Variables:
  height_above_mean_sea_level
===========================

===========================
Reader: c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
Projection:
  +proj=latlong
Coverage: [degrees]
  xmin: 9.000000   xmax: 16.000000   step: 0.041667   numx: 168
  ymin: 38.020832   ymax: 42.979168   step: 0.0416679   numy: 119
  Corners (lon, lat):
    (  9.00,  42.98)  ( 16.00,  42.98)
    (  9.00,  38.02)  ( 16.00,  38.02)
Vertical levels [m]:
  [-1.0182366]
Available time range:
  start: 2021-10-10 00:30:00   end: 2021-10-15 23:30:00   step: 1:00:00
    144 times (0 missing)
Variables:
  northward_sea_water_velocity
  eastward_sea_water_velocity
  y_sea_water_velocity
  x_sea_water_velocity`

What is wrong?
Thank's for your help.
Best regards

**Comment by knutfrode** [comment]
Ok, so I guess that this is then really bathymetry, only that it is positive over land, and negative at sea(?)
This can then probably not be used directly by OpenDrift as is, as standard_name `sea_floor_depth_below_sea_level` is expected.
Some mapping could be made, but for running that example, you could e.g. instead use bathymetry from this source (North Atlantic):
`https://thredds.met.no/thredds/dodsC/cmems/topaz6/dataset-topaz6-arc-15min-3km-be.ncml` 
But this has then to be added last in the list, otherwise currents will also be obtained from this reader, and not from your own current file.

**Comment by oceandiff** [comment]
Ok, I have modified the gebco file, I have changed the name in sea_floor_depth_below_sea _level, and now I can read the bathymetry, but I have a new item, this is the output of the run:

`21:20:49 INFO    opendrift.models.basemodel: OpenDriftSimulation initialised (version 1.7.1 / v1.7.1-124-g9339ac5-dirty)
21:20:49 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
21:20:49 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
21:20:49 INFO    opendrift.readers.basereader: Variable y_sea_water_velocity will be rotated from northward_sea_water_velocity
21:20:49 INFO    opendrift.readers.basereader: Variable x_sea_water_velocity will be rotated from eastward_sea_water_velocity
21:20:50 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\wave.nc
21:20:50 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
21:20:50 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\gebco_2021_BATHY.nc
21:20:50 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
===========================
Reader: c:\users\opendrift\tests\test_data\gebco_2021_BATHY.nc
Projection:
  +proj=latlong
Coverage: [degrees]
  xmin: -0.589583   xmax: 23.639583   step: 0.00416667   numx: 5816
  ymin: 34.960417   ymax: 46.139583   step: 0.00416667   numy: 2683
  Corners (lon, lat):
    ( -0.59,  46.14)  ( 23.64,  46.14)
    ( -0.59,  34.96)  ( 23.64,  34.96)
Vertical levels [m]:
  Not specified
Available time range:
  start: None   end: None   step: None
Variables:
  sea_floor_depth_below_sea_level
===========================

===========================

21:20:50 INFO    opendrift.models.basemodel: ========================
21:20:50 INFO    opendrift.models.basemodel: Exception:
21:20:50 INFO    opendrift.models.basemodel: Cannot convert fill_value nan to dtype int16
21:20:50 INFO    opendrift.models.basemodel: ========================
21:20:50 INFO    opendrift.models.basemodel: Seeding elements 5.000000 meters above seafloor
21:20:50 INFO    opendrift.models.basemodel: Fallback values will be used for the following variables which have no readers:
21:20:50 INFO    opendrift.models.basemodel:    upward_sea_water_velocity: 0.000000
21:20:50 INFO    opendrift.models.basemodel:    ocean_vertical_diffusivity: 0.020000
21:20:50 INFO    opendrift.models.basemodel:    ocean_mixed_layer_thickness: 50.000000
21:20:50 INFO    opendrift.models.basemodel: Adding a dynamical landmask with max. priority based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
21:20:53 INFO    opendrift.models.basemodel: Using existing reader for land_binary_mask
21:20:53 INFO    opendrift.models.basemodel: All points are in ocean
21:20:54 INFO    opendrift.models.basemodel: ========================
21:20:54 INFO    opendrift.models.basemodel: Exception:
21:20:54 INFO    opendrift.models.basemodel: Cannot convert fill_value nan to dtype int16
21:20:54 INFO    opendrift.models.basemodel: ========================
21:20:54 INFO    opendrift.models.basemodel: 2021-10-10 00:30:00 - step 1 of 144 - 10000 active elements (0 deactivated)
21:20:54 INFO    opendrift.models.basemodel: ========================
21:20:54 INFO    opendrift.models.basemodel: Exception:
21:20:54 INFO    opendrift.models.basemodel: Cannot convert fill_value nan to dtype int16
21:20:54 INFO    opendrift.models.basemodel: ========================
21:20:54 INFO    opendrift.models.basemodel: 2021-10-10 01:00:00 - step 2 of 144 - 10000 active elements (0 deactivated)
21:20:55 WARNING opendrift.readers.basereader.structured: Data block from c:\users\alessandro.mercatini\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc not large enough to cover element positions within timestep. Buffer size (3) must be increased. See `Variables.set_buffer_size`.
21:20:55 WARNING opendrift.readers.basereader.structured: Data block from c:\users\alessandro.mercatini\opendrift\tests\test_data\wave.nc not large enough to cover element positions within timestep. Buffer size (3) must be increased. See `Variables.set_buffer_size`.
21:20:55 INFO    opendrift.models.basemodel: ========================
21:20:55 INFO    opendrift.models.basemodel: Exception:
21:20:55 INFO    opendrift.models.basemodel: Cannot convert fill_value nan to dtype int16
21:20:55 INFO    opendrift.models.basemodel: ========================
21:20:55 WARNING opendrift.models.basemodel: Missing variables: ['land_binary_mask']
21:20:55 INFO    opendrift.models.basemodel: 2021-10-10 01:30:00 - step 3 of 144 - 9977 active elements (23 deactivated)
21:20:55 WARNING opendrift.readers.basereader.structured: Data block from c:\users\alessandro.mercatini\opendrift\tests\test_data\wave.nc not large enough to cover element positions within timestep. Buffer size (3) must be increased. See `Variables.set_buffer_size`.
21:20:55 INFO    opendrift.models.basemodel: ========================
21:20:55 INFO    opendrift.models.basemodel: Exception:
21:20:55 INFO    opendrift.models.basemodel: Cannot convert fill_value nan to dtype int16
21:20:55 INFO    opendrift.models.basemodel: ========================
.
.
.
.
.
===========================
--------------------
Reader performance:
--------------------
c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
 0:00:00.8  total
 0:00:00.0  preparing
 0:00:00.7  reading
 0:00:00.4  interpolation
 0:00:00.0  interpolation_time
 0:00:00.0  masking
--------------------
c:\users\opendrift\tests\test_data\wave.nc
 0:00:01.6  total
 0:00:00.0  preparing
 0:00:01.5  reading
 0:00:01.0  interpolation
 0:00:00.0  interpolation_time
 0:00:00.0  masking
--------------------
c:\users\opendrift\tests\test_data\gebco_2021_BATHY.nc
         0  total
 0:00:00.0  preparing
         0  reading
--------------------
constant_reader
 0:00:00.0  total
 0:00:00.0  preparing
 0:00:00.0  reading
         0  masking
--------------------
global_landmask
 0:00:00.8  total
 0:00:00.1  preparing
 0:00:00.7  reading
 0:00:00.0  masking
--------------------
Performance:
   53.1 total time
    0.9 configuration
     10.6 readers
        2.7 c:\users\opendrift\tests\test_data\gebco_2021_BATHY.nc
        2.1 postprocessing
    4.0 preparing main loop
      3.1 making dynamical landmask
      0.2 moving elements to ocean
        1.0 global_landmask
   47.5 main loop
        1.0 c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
        1.9 c:\users\opendrift\tests\test_data\wave.nc
        0.1 constant_reader
     25.4 updating elements
       21.9 vertical mixing
    0.5 cleaning up
--------------------
===========================
Model:  SedimentDrift     (OpenDrift version 1.7.1)
        9976 active SedimentElement particles  (24 deactivated, 0 scheduled)
-------------------
Environment variables:
  -----
  x_sea_water_velocity
  y_sea_water_velocity
     1) c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
  -----
  sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment
  sea_surface_wave_period_at_variance_spectral_density_maximum
  sea_surface_wave_stokes_drift_x_velocity
  sea_surface_wave_stokes_drift_y_velocity
     1) c:\users\opendrift\tests\test_data\wave.nc
  -----
  sea_floor_depth_below_sea_level
     1) c:\users\opendrift\tests\test_data\gebco_2021_BATHY.nc
  -----
  x_wind
  y_wind
     1) constant_reader
  -----
  land_binary_mask
     1) global_landmask
  -----
Readers not added for the following variables:
  ocean_mixed_layer_thickness
  ocean_vertical_diffusivity
  upward_sea_water_velocity

Time:
        Start: 2021-10-10 00:30:00
        Present: 2021-10-13 00:30:00
        Calculation steps: 144 * 0:30:00 - total time: 3 days, 0:00:00
        Output steps: 145 * 0:30:00
-------------------
"Missing variables: ['land_binary_mask']", "Missing variables: ['land_binary_mask']"
===========================`

anyone can help me, please?

**Comment by oceandiff** [comment]
Thank you Knut, I have modified the file, now in the ocean the data are positive, and 0 at land. When I run the example now I don't have any error, but the reader is not used:
`
13:29:32 INFO    opendrift.models.basemodel: OpenDriftSimulation initialised (version 1.7.1 / v1.7.1-124-g9339ac5-dirty)
13:29:32 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
13:29:32 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
13:29:32 INFO    opendrift.readers.basereader: Variable y_sea_water_velocity will be rotated from northward_sea_water_velocity
13:29:32 INFO    opendrift.readers.basereader: Variable x_sea_water_velocity will be rotated from eastward_sea_water_velocity
13:29:32 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\alessandro.mercatini\opendrift\tests\test_data\wave.nc
13:29:32 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
13:29:32 INFO    opendrift.readers.reader_netCDF_CF_generic: Opening dataset: c:\users\opendrift\tests\test_data\gebco_2021_BATHY_inv.nc
13:29:32 INFO    opendrift.readers.reader_netCDF_CF_generic: Grid coordinates are detected, but proj4 string not given: assuming latlong
===========================
Reader: c:\users\opendrift\tests\test_data\gebco_2021_BATHY_inv.nc
Projection:
  +proj=latlong
Coverage: [degrees]
  xmin: -0.589583   xmax: 23.639583   step: 0.00416667   numx: 5816
  ymin: 34.960417   ymax: 46.139583   step: 0.00416667   numy: 2683
  Corners (lon, lat):
    ( -0.59,  46.14)  ( 23.64,  46.14)
    ( -0.59,  34.96)  ( 23.64,  34.96)
Vertical levels [m]:
  Not specified
Available time range:
  start: None   end: None   step: None
Variables:
  height_above_mean_sea_level
===========================

13:29:32 INFO    opendrift.models.basemodel: Fallback values will be used for the following variables which have no readers:
13:29:32 INFO    opendrift.models.basemodel:    upward_sea_water_velocity: 0.000000
13:29:32 INFO    opendrift.models.basemodel:    ocean_vertical_diffusivity: 0.020000
13:29:32 INFO    opendrift.models.basemodel:    ocean_mixed_layer_thickness: 50.000000
13:29:32 INFO    opendrift.models.basemodel:    **sea_floor_depth_below_sea_level: 0.000000**
13:29:32 INFO    opendrift.models.basemodel: Adding a dynamical landmask with max. priority based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
13:29:34 INFO    opendrift.models.basemodel: Using existing reader for land_binary_mask
13:29:34 INFO    opendrift.models.basemodel: All points are in ocean
13:29:35 INFO    opendrift.models.basemodel: 2021-10-10 00:30:00 - step 1 of 288 - 10000 active elements (0 deactivated)
.
.
.
.
.
.

===========================
Model:  SedimentDrift     (OpenDrift version 1.7.1)
        10000 active SedimentElement particles  (0 deactivated, 0 scheduled)
-------------------
Environment variables:
  -----
  x_sea_water_velocity
  y_sea_water_velocity
     1) c:\users\opendrift\tests\test_data\med-cmcc-cur-an-fc-h_1634028851697new.nc
  -----
  sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment
  sea_surface_wave_period_at_variance_spectral_density_maximum
  sea_surface_wave_stokes_drift_x_velocity
  sea_surface_wave_stokes_drift_y_velocity
     1) c:\users\opendrift\tests\test_data\wave.nc
  -----
  x_wind
  y_wind
     1) constant_reader
  -----
  land_binary_mask
     1) global_landmask
  -----
**Readers not added for the following variables:
  ocean_mixed_layer_thickness
  ocean_vertical_diffusivity
  sea_floor_depth_below_sea_level
  upward_sea_water_velocity

Discarded readers:
  c:\users\opendrift\tests\test_data\gebco_2021_BATHY_inv.nc**

Time:
        Start: 2021-10-10 00:30:00
        Present: 2021-10-13 00:30:00
        Calculation steps: 288 * 0:15:00 - total time: 3 days, 0:00:00
        Output steps: 145 * 0:30:00
===========================
`

any idea?

**Comment by knutfrode** [comment]
Can you post your whole script?

Btw, if you ad three triple backquotes (```) on an empty line before your code sample and logs, and the same after, it will be more easily readable. You can click the "preview" tab to see how it is displayed at GitHub.

**Comment by oceandiff** [comment]
Hi Knut,
first of all sorry for misunderstanding your quote advice :)

Btw, now the model run correctly, but after the few first steps I have the following working: 

'''
pendrift.readers.basereader.structured: Data block from gebco_2021_BATHY.nc not large enough to cover element positions within timestep. Buffer size (10) must be increased. See `Variables.set_buffer_size`.
'''

what's the reason?
Thank you, I hope this is the last time (about this).
