### ISSUE TITLE
density map from basemodel error

### ISSUE THREAD

**Issue by oceandiff** [OpenDrift/opendrift#802]
Hi,
I'm triing to add a density map via the command `o.write_netcdf_density_map('densiyt.nc', pixelsize_m=300)`, but when I run the model I've the following error:

`Traceback (most recent call last):
  File "C:\Users\opendrift\examples\test\ml\example_plast.py", line 35, in <module>
    o.write_netcdf_density_map('densiyt.nc', pixelsize_m=300)
  File "c:\users\opendrift\opendrift\models\basemodel.py", line 4762, in write_netcdf_density_map
    nc = Dataset(filename, 'w')
NameError: name 'Dataset' is not defined`

Where is the problem?
Thanks in advance

**Comment by knutfrode** [comment]
Hi,
An important statement had apparently disappeared.
I have now re-inserted this, and it should work again if you update your code.

**Comment by oceandiff** [comment]
Thank you.

**Comment by oceandiff** [comment]
Does anyone please let me know what is the formula behind the density map calculation?
Thanks

**Comment by knutfrode** [comment]
Here is the source code of `write_netcdf_density_map`:
https://opendrift.github.io/_modules/opendrift/models/basemodel.html#OpenDriftSimulation.write_netcdf_density_map
which uses `get_density_array`:
https://opendrift.github.io/_modules/opendrift/models/basemodel.html#OpenDriftSimulation.get_density_array

So this is simply 2d histogram, which can be weighted by any element property.
