### ISSUE TITLE
Opening a file to plot

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#895]
Hi, 

I use to do quick plots of OpenDrift  output files with 

import opendrift
import numpy as np
o = opendrift.open("archivo.nc", elements=np.arange(0,392000,100))
o.plot(filename="archivo.png",linecolor="z",fast = True, corners=[-74.5,-73.0,-43.0,-41.0])
o.animation(filename="archivo.mp4",linecolor="z",fast = True)

However I am getting this error, using v1.7.3

>>> o = opendrift.open("Traj_Horarias_1-10_Ancud_Y1.nc",elements=np.arange(0,100,10))
09:26:23 DEBUG   opendrift.models.basemodel: Adding 17 config items from basemodel
09:26:23 DEBUG   opendrift.models.basemodel: Adding 4 config items from basemodel
09:26:23 DEBUG   opendrift.models.basemodel: Adding 36 config items from basemodel
09:26:23 INFO    opendrift.models.basemodel: OpenDriftSimulation initialised (version 1.7.3 / v1.7.3-77-g7930fe8-dirty)
09:26:23 DEBUG   opendrift.models.basemodel: Adding 14 config items from oceandrift
09:26:23 DEBUG   opendrift.models.basemodel:   Overwriting config item seed:z
09:26:23 DEBUG   opendrift.export.io_netcdf: Importing from Traj_Horarias_1-10_Ancud_Y1.nc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matlab/opendrift/opendrift/__init__.py", line 76, in open
    o.io_import_file(filename, times=times, elements=elements, load_history=load_history)
  File "/home/matlab/opendrift/opendrift/export/io_netcdf.py", line 286, in import_file
    self.status_categories = infile.variables['status'].flag_meanings.split()
  File "src/netCDF4/_netCDF4.pyx", line 4372, in netCDF4._netCDF4.Variable.__getattr__
  File "src/netCDF4/_netCDF4.pyx", line 4178, in netCDF4._netCDF4.Variable.getncattr
  File "src/netCDF4/_netCDF4.pyx", line 1468, in netCDF4._netCDF4._get_att
  File "src/netCDF4/_netCDF4.pyx", line 1950, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: Attribute not found

What could it be?

**Comment by knutfrode** [comment]
From the error, it seems like your input file is missing the variable "status". Is this file an "untouched" output file from OpenDrift?

However, there seems to be a mismatch between your codelines and the error, as filename is `archivo.no` in the code, and `Traj_Horarias_1-10_Ancud_Y1.nc` in the error message?

**Comment by AndresSepulveda** [comment]
Somehow the attributes are missing from the status variable. 

I've added with

ncatted -O -a flag_meanings,status,c,c,"active missing_data"
ncatted -O -a coordinates,status,c,c,"lat lon time"
ncatted -O -a flag_values,status,c,s,'0, 1'
ncatted -O -a valid_range,status,c,s,'0, 1'

but I can only open the file using

o.open_xarray

and 

o.plot gives the following error

>>> o.plot(filename="b.pg",fast=True)
13:29:38 DEBUG   opendrift.models.basemodel: Finding min longitude...
13:29:38 DEBUG   opendrift.models.basemodel: Finding max longitude...
13:29:39 DEBUG   opendrift.models.basemodel: Finding min latitude...
13:29:39 DEBUG   opendrift.models.basemodel: Finding max latitude...
13:29:39 WARNING opendrift.models.basemodel: Plotting fast. This will make your plots less accurate.
13:29:39 DEBUG   opendrift_landmask_data.mask: memmapping mask..
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matlab/opendrift/opendrift/models/basemodel.py", line 4196, in plot
    ax.scatter(x[index_of_first, range(x.shape[1])],
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/dataarray.py", line 707, in __getitem__
    return self.isel(indexers=self._item_key_to_dict(key))
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1122, in isel
    ds = self._to_temp_dataset()._isel_fancy(
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/dataset.py", line 2139, in _isel_fancy
    new_var, new_index = isel_variable_and_index(
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/indexes.py", line 106, in isel_variable_and_index
    new_variable = variable.isel(indexers)
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/variable.py", line 1166, in isel
    return self[key]
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/variable.py", line 810, in __getitem__
    dims, indexer, new_order = self._broadcast_indexes(key)
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/variable.py", line 656, in _broadcast_indexes
    return self._broadcast_indexes_outer(key)
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/variable.py", line 732, in _broadcast_indexes_outer
    return dims, OuterIndexer(tuple(new_key)), None
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.9/site-packages/xarray/core/indexing.py", line 417, in __init__
    raise TypeError(
TypeError: invalid indexer array, does not have integer dtype: array(None, dtype=object)
>>>

**Comment by knutfrode** [comment]
The status attributes are added to the file before closing, and their absence indicate that this simulation has been aborted/crashed before it was finished. Thus this file might not be readable without hacking the import- and plot- methods.
Is it a possibility to run the simulation again?
I can also recommend updating the the latest version (1.9.0), as improvements and fixes are constantly added. Remember then also to update dependencies (https://opendrift.github.io/install.html)

**Comment by AndresSepulveda** [comment]
That must be it, somehow it crashed. I am running again those simulations and they end well.

I will update soon...
